# Site settings
name: 李鹏
location: 山西吕梁
company: 大连民族大学
position: 22年应届生
phone: 17835419329
wechat: li17835419329
qq: 1218744179
email: 1218744179@qq.com



permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

